// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProfile(arg1) {
  return window['go']['api']['ConnectionAPI']['DeleteProfile'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['api']['ConnectionAPI']['GetProfile'](arg1);
}

export function ListProfiles() {
  return window['go']['api']['ConnectionAPI']['ListProfiles']();
}

export function SaveProfile(arg1) {
  return window['go']['api']['ConnectionAPI']['SaveProfile'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['api']['ConnectionAPI']['TestConnection'](arg1);
}

export function TestConnectionProfile(arg1) {
  return window['go']['api']['ConnectionAPI']['TestConnectionProfile'](arg1);
}
