// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function DeleteProfile(arg1:domain.ConnProfileID):Promise<void>;

export function GetProfile(arg1:domain.ConnProfileID):Promise<domain.ConnProfile>;

export function ListProfiles():Promise<Array<domain.ConnProfile>>;

export function SaveProfile(arg1:domain.ConnProfile):Promise<void>;

export function TestConnection(arg1:domain.ConnProfileID):Promise<domain.ConnectionTestResult>;

export function TestConnectionProfile(arg1:domain.ConnProfile):Promise<domain.ConnectionTestResult>;
