// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetObjectInfo(arg1:domain.ConnProfileID,arg2:string,arg3:string,arg4:string,arg5:domain.ExplorerObjectKind):Promise<domain.ObjectInfo>;

export function GetTableInfo(arg1:domain.ConnProfileID,arg2:string,arg3:string,arg4:string):Promise<domain.TableInfo>;

export function ListDatabases(arg1:domain.ConnProfileID):Promise<Array<domain.ExplorerDatabase>>;

export function ListSchemaObjects(arg1:domain.ConnProfileID,arg2:string,arg3:string):Promise<Array<domain.ExplorerObject>>;

export function ListSchemas(arg1:domain.ConnProfileID,arg2:string):Promise<Array<domain.ExplorerSchema>>;
