// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function CancelJob(arg1:domain.ConnProfileID,arg2:domain.JobID):Promise<void>;

export function DisposeJob(arg1:domain.ConnProfileID,arg2:domain.JobID):Promise<void>;

export function GetJob(arg1:domain.ConnProfileID,arg2:domain.JobID):Promise<domain.JobSummary>;

export function GetResultSchema(arg1:domain.ConnProfileID,arg2:domain.GetResultSchemaRequest):Promise<domain.ResultSchema>;

export function GetRows(arg1:domain.ConnProfileID,arg2:domain.GetRowsRequest):Promise<domain.GetRowsResponse>;

export function RunQuery(arg1:domain.RunQueryRequest):Promise<domain.RunQueryResponse>;
