// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1, arg2) {
  return window['go']['api']['QueryAPI']['CancelJob'](arg1, arg2);
}

export function DisposeJob(arg1, arg2) {
  return window['go']['api']['QueryAPI']['DisposeJob'](arg1, arg2);
}

export function GetJob(arg1, arg2) {
  return window['go']['api']['QueryAPI']['GetJob'](arg1, arg2);
}

export function GetResultSchema(arg1, arg2) {
  return window['go']['api']['QueryAPI']['GetResultSchema'](arg1, arg2);
}

export function GetRows(arg1, arg2) {
  return window['go']['api']['QueryAPI']['GetRows'](arg1, arg2);
}

export function RunQuery(arg1) {
  return window['go']['api']['QueryAPI']['RunQuery'](arg1);
}
