// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function LoadWorkspace():Promise<domain.ScriptWorkspace>;

export function SaveScript(arg1:domain.SaveScriptRequest):Promise<domain.SaveScriptResponse>;

export function SaveWorkspace(arg1:domain.ScriptWorkspace):Promise<void>;
