// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadWorkspace() {
  return window['go']['api']['ScriptAPI']['LoadWorkspace']();
}

export function SaveScript(arg1) {
  return window['go']['api']['ScriptAPI']['SaveScript'](arg1);
}

export function SaveWorkspace(arg1) {
  return window['go']['api']['ScriptAPI']['SaveWorkspace'](arg1);
}
